eureka:
  instance:
    prefer-ip-address: true #注册使用ip
    instance-id: 192.168.2.107:${server.port} #实例id
    ip-address: 192.168.2.107 #可访问的ip地址

spring:
  data:
    mongodb:
      database: speech
      host: 192.168.2.107:27017
      username: admin
      password: admin

ali-props:
  app-key: "自己的appkey"
  access-key-id: "自己的keyId"
  access-key-secret: "自己的密钥"

baidu-props:
  app-id: "自己的appid"
  api-key: "自己的apikey"
  secret-key: "自己的密钥"

